### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by nanopone** [ChrisMalnick/xx3dsfml#11]
this is the error i get
![Screenshot_20240326_191030](https://github.com/ChrisMalnick/xx3dsfml/assets/49787675/7020d616-a8af-4d2b-a755-bc9b62bbf684)
i did find that `sf::Keyboard::Apostrophe:` might actually need to be `sf::Keyboard::Quote:`, but i could not solve the setprocessinginterval issue. i'm not a c++ dev so i have nothing else to add unfortunately.

**Comment by Lorenzooone** [comment]
If you try to build https://github.com/ChrisMalnick/xx3dsfml/pull/6 (so download it from https://github.com/Lorenzooone/xx3dsfml/tree/new_main_changes ), does it work?
You will need to run the following commands:
`
make download_ftd3xx
make
`
I recently tried installing this on a different PC, and I noticed that as well.
Hopefully this should help.

**Comment by ChrisMalnick** [comment]
The `setProcessingInterval` call doesn't actually seem to do all that much as far as I can tell, but what it does manage to do is let you know if you have an older version of SFML! :P

Your solution would have been to either just remove it (which in hindsight, I should have just left in the README) or to update SFML to version 2.6.1 if possible, but of course, you could also just follow what @Lorenzooone suggested!

**Comment by ChrisMalnick** [comment]
Support for older versions of SFML has been added as of release v1.4.0 by removing the setProcessingInterval call and reverting to the deprecated key enumerations. Migration to the newer key enumerations will be handled if and when the deprecated key enumerations go out of support being that there will then be an explicit SFML version to reference in a preprocessor directive to handle it, but as for now, this should no longer be an issue.
